import React,{useMemo,useState} from "react";
import {Link,useNavigate,useSearchParams} from "react-router-dom";
import {CheckCircle2,Clock3,FileText,ShieldCheck,ShieldAlert,BriefcaseBusiness,UploadCloud,MapPinned,Search,Download,Filter,Plus,Eye,Check,AlertTriangle,History,UserCheck,Building2,ClipboardCheck,RefreshCcw,LockKeyhole} from "lucide-react";
import {useDemo} from "../context/DemoContext";
import PageHeader from "../components/ui/PageHeader";
import StatusBadge from "../components/ui/StatusBadge";
import TrustScore from "../components/ui/TrustScore";
import {PlacementChart,RetentionChart,WageChart,OutcomeChart} from "../components/charts/OutcomeCharts";

const followups=[["30 Days","12 Aug 2026","Completed","Phone","Employed"],["90 Days","11 Sep 2026","Completed","WhatsApp","Still employed"],["180 Days","10 Dec 2026","Due in 5 days","Phone","—"],["365 Days","08 Jun 2027","Upcoming","—","—"]];
const docs=[["Joining Letter.pdf","12 Sep 2026","Verified","Provider Admin"],["Payslip_Aug.pdf","14 Sep 2026","Verified","Provider Admin"],["ID Card.pdf","12 Sep 2026","Pending","—"],["Business Photo.jpg","08 Sep 2026","Verified","Field Officer"],["Invoice.pdf","07 Sep 2026","Pending","—"],["Udyam Certificate.pdf","05 Sep 2026","Rejected","Provider Admin"]];
const courses=[["Full Stack Web Development","Digital Bharat Academy","IT-ITeS","NSQF 5","24 weeks",218,84,79],["Advanced Solar Technician","UP SkillWorks","Green Jobs","NSQF 4","20 weeks",186,81,83],["EV Service Associate","AutoSkill Hub","Automotive","NSQF 4","18 weeks",164,74,72],["Digital Marketing","Digital Bharat Academy","IT-ITeS","NSQF 5","16 weeks",142,71,76]];
const providers=[["ABC Skill Development Centre","UP-ABC-021","Ghaziabad",12,486,"82.4%","79%","84"],["UP SkillWorks","UP-USW-118","Ghaziabad",18,721,"81.7%","83%","86"],["Digital Bharat Academy","UP-DBA-044","Lucknow",15,608,"78.9%","76%","81"],["AutoSkill Hub","UP-ASH-077","Noida",9,344,"74.1%","72%","73"]];

function Section({title,eyebrow,children,action}){return <div className="panel pageSection"><div className="panelHead"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h3>{title}</h3></div>{action}</div>{children}</div>}
function Kpis({items}){return <div className="metricGrid">{items.map((x,i)=><div className="miniKpi" key={i}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div>}
function DataTable({headers,rows,onRow}){return <div className="tablePanel"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} onClick={()=>onRow&&onRow(r)}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}

export function AdminAnalyticsPage(){return <div className="page"><PageHeader eyebrow="ADMIN / ANALYTICS" title="Outcome analytics" sub="Evidence-backed intelligence across geography, courses, providers and the complete outcome funnel."/><div className="filters"><select><option>All states</option><option>Uttar Pradesh</option></select><select><option>All districts</option><option>Ghaziabad</option><option>Lucknow</option><option>Noida</option></select><select><option>All sectors</option><option>IT-ITeS</option><option>Green Jobs</option></select><select><option>Last 12 months</option><option>Last 90 days</option></select></div><Kpis items={[["Completion","87.3%"],["Outcome captured","86.0%"],["Verification coverage","84.6%"],["Follow-up completion","79.2%"],["Average trust","81/100"],["Active anomalies","17"]]}/><div className="grid2"><Section title="Geographic outcomes" eyebrow="DISTRICT PULSE"><div className="split3">{[["Ghaziabad","82% placement"],["Lucknow","79% placement"],["Noida","76% placement"]].map(x=><div className="miniKpi" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>Retention: {x[0]==="Ghaziabad"?"84":"78"}%</small></div>)}</div></Section><Section title="Outcome funnel" eyebrow="SYSTEM CONVERSION"><div className="funnel"><div style={{width:"100%"}}>ENROLLED <b>4,821</b></div><div style={{width:"90%"}}>COMPLETED <b>4,210</b></div><div style={{width:"78%"}}>CERTIFIED <b>3,982</b></div><div style={{width:"67%"}}>OUTCOME CAPTURED <b>3,622</b></div><div style={{width:"57%"}}>VERIFIED <b>3,071</b></div><div style={{width:"47%"}}>RETAINED <b>2,485</b></div></div></Section></div><div className="grid2"><Section title="Course performance" eyebrow="PLACEMENT BY COURSE"><div className="chartBox"><PlacementChart/></div></Section><Section title="Employment retention" eyebrow="30 / 90 / 180 / 365 DAYS"><div className="chartBox"><RetentionChart/></div></Section></div><div className="grid2"><Section title="Wage progression" eyebrow="MEDIAN WAGE BAND INDEX"><div className="chartBox"><WageChart/></div></Section><Section title="Outcome distribution" eyebrow="CURRENT STATE"><div className="chartBox"><OutcomeChart/></div></Section></div><Section title="Data quality" eyebrow="TRUST & COMPLETENESS"><div className="progressRow"><span>Employer confirmation</span><b>84%</b><div><i style={{width:"84%"}}/></div></div><div className="progressRow"><span>Documents verified</span><b>79%</b><div><i style={{width:"79%"}}/></div></div><div className="progressRow"><span>Missing outcomes</span><b>11%</b><div><i style={{width:"11%"}}/></div></div><div className="progressRow"><span>Consent coverage</span><b>96%</b><div><i style={{width:"96%"}}/></div></div></Section></div>}

export function AdminOutcomesPage(){const {data,updateTrainee}=useDemo();const [params]=useSearchParams();const [q,setQ]=useState(params.get("search")||"");const [filter,setFilter]=useState("All");const [selected,setSelected]=useState([]);const rows=data.trainees.filter(t=>(filter==="All"||t.outcome===filter)&&(`${t.name} ${t.id} ${t.course}`.toLowerCase().includes(q.toLowerCase())));return <div className="page"><PageHeader eyebrow="ADMIN / OUTCOMES" title="Outcome registry" sub="Search, inspect and verify outcome records without automatically rejecting any record." action={<button className="btn ghost" onClick={()=>alert("Demo CSV export prepared.")}><Download size={15}/> Export CSV</button>}/><div className="filters"><div className="search"><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search trainee, ID or course"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Employed</option><option>Self-employed</option><option>Seeking work</option></select><button className="btn" onClick={()=>setSelected(rows.map(x=>x.id))}><Filter size={14}/> Select visible</button></div>{selected.length>0&&<div className="notice">{selected.length} records selected for verification review. <button className="btn primary" onClick={()=>{selected.forEach(id=>updateTrainee(id,{verification:"Verification requested"}));setSelected([])}}>Request verification</button></div>}<DataTable headers={["Trainee","Outcome","Employer","Wage band","Source","Trust","Verification","Anomaly",""]} rows={rows.map(t=>[<><b>{t.name}</b><small>{t.id}</small></>,<StatusBadge type={t.outcome==="Seeking work"?"warning":"positive"}>{t.outcome}</StatusBadge>,t.employer,t.wage,t.verification,<TrustScore value={t.trust}/>,<StatusBadge type={t.verification==="Verified"?"positive":"warning"}>{t.verification}</StatusBadge>,t.anomaly?<StatusBadge type="warning">FLAGGED</StatusBadge>:"—",<Link className="rowLink" to={`/provider/trainees/${t.id}`}>Open</Link>])}/></div>}

export function ProviderAnalyticsPage(){return <div className="page"><PageHeader eyebrow="PROVIDER / ANALYTICS" title="Provider performance" sub="Measure placement, retention, wage progression, relevance and outcome trust for your training portfolio."/><Kpis items={[["Trainees","1,248"],["Placement","78.4%"],["3M retention","82%"],["6M retention","76%"],["12M retention","68%"],["Trust score","81"]]}/><div className="grid2"><Section title="Placement by course"><div className="chartBox"><PlacementChart/></div></Section><Section title="Retention durability"><div className="chartBox"><RetentionChart/></div></Section></div><div className="grid2"><Section title="Wage progression"><div className="chartBox"><WageChart/></div></Section><Section title="Outcome distribution"><div className="chartBox"><OutcomeChart/></div></Section></div></div>}

export function FollowupCenterPage({traineeMode=false}){const {data,updateTrainee}=useDemo();const [done,setDone]=useState(false);return <div className="page"><PageHeader eyebrow={traineeMode?"TRAINEE / FOLLOW-UPS":"OUTCOME / FOLLOW-UP CENTER"} title="Follow-up timeline" sub="Retention is measured at 30, 90, 180 and 365 days, with channel and response evidence."/><Section title={traineeMode?"Amit Sharma — SO-2026-00481":"Follow-up operations"} eyebrow="CASE-AS-20260924"><div className="timelineWide">{followups.map((x,i)=><div className="timelineItem" key={x[0]}><b>{x[0]} · {x[2]}</b><span>{x[1]} • Channel: {x[3]} • Response: {x[4]}</span>{i===2&&!done&&<button className="btn primary" style={{marginTop:8}} onClick={()=>{setDone(true);updateTrainee("KSL-2026-00481",{followup:"180-day completed"})}}>Complete follow-up</button>}{i===2&&done&&<StatusBadge type="positive">COMPLETED IN DEMO</StatusBadge>}</div>)}</div></Section><Section title="Manual response simulation" eyebrow="DEMO CONTROL"><div className="formGrid"><label>Channel<select><option>Phone</option><option>WhatsApp</option><option>Field visit</option></select></label><label>Response<select><option>Still employed</option><option>Wage increased</option><option>Changed job</option><option>Seeking work</option></select></label><label style={{gridColumn:"1/-1"}}>Notes<textarea defaultValue="Trainee confirmed current employment and continued use of trained skills."/></label></div><button className="btn primary" onClick={()=>alert("Follow-up response saved to demo state.")}>Save response</button></Section></div>}

export function DocumentsPage({traineeMode=false}){const [docsState,setDocs]=useState(docs);return <div className="page"><PageHeader eyebrow={traineeMode?"TRAINEE / DOCUMENTS":"DOCUMENT CENTER"} title="Evidence & documents" sub="Documents are evidence signals; verification status is visible and auditable." action={!traineeMode&&<button className="btn primary"><UploadCloud size={15}/> Upload document</button>}/><div className="filters"><select><option>All document types</option><option>Joining Letter</option><option>Payslip</option><option>ID Card</option></select><select><option>All statuses</option><option>Verified</option><option>Pending</option><option>Rejected</option></select></div><div className="cards">{docsState.map((d,i)=><div className="docCard" key={d[0]}><FileText size={23}/><div style={{flex:1}}><b>{d[0]}</b><span>Uploaded {d[1]} • Verified by {d[3]}</span></div><StatusBadge type={d[2]==="Verified"?"positive":d[2]==="Rejected"?"warning":"neutral"}>{d[2]}</StatusBadge>{!traineeMode&&d[2]==="Pending"&&<button className="btn" onClick={()=>setDocs(a=>a.map((x,j)=>j===i?[...x.slice(0,2),"Verified", "Provider Admin"]:x))}><Check size={14}/></button>}</div>)}</div></div>}

export function ConsentPage(){const [items,setItems]=useState([["Follow-up contact",true],["Employer contact",true],["Document upload",true],["Analytics",true],["Job sharing",false]]);return <div className="page"><PageHeader eyebrow="TRAINEE / PRIVACY" title="Consent center" sub="Granular permissions make outcome tracking transparent and reversible."/><Section title="Permission ledger" eyebrow="CURRENT CONSENTS">{items.map(([n,v],i)=><div className="consent" key={n}><span><b>{n}</b><small style={{display:"block",color:"#607873",marginTop:4}}>{v?"Granted on 12 Sep 2026":"Not granted"}</small></span><button className={"btn "+(v?"primary":"ghost")} onClick={()=>setItems(a=>a.map((x,j)=>j===i?[x[0],!x[1]]:x))}>{v?"Granted":"Grant"}</button></div>)}</Section><Section title="Consent history" eyebrow="AUDITABLE"><div className="timeline">{["12 Sep 2026 — Follow-up contact granted","12 Sep 2026 — Analytics granted","13 Sep 2026 — Job sharing withdrawn"].map(x=><div key={x}><i/><div><b>{x}</b><small>Recorded with consent version 2.1</small></div></div>)}</div></Section></div>}

export function TrainingPage(){return <div className="page"><PageHeader eyebrow="TRAINEE / TRAINING" title="Training record" sub="A verified training and certification history connected to your outcome record."/><div className="detailHero"><div><span className="eyebrow">CERTIFIED PROGRAMME</span><h2>Full Stack Web Development</h2><p>ABC Skill Development Centre • Batch WEB-26-B07</p></div><StatusBadge type="positive">CERTIFICATE VERIFIED</StatusBadge></div><Kpis items={[["Enrollment","14 Jan 2026"],["Completion","28 Jun 2026"],["Attendance","94%"],["Assessment","82%"],["Certificate","CERT-UP-26-481"],["NSQF level","Level 5"]]}/><Section title="Training relevance" eyebrow="SKILL UTILISATION"><div className="progressRow"><span>Current role uses trained skills</span><b>86%</b><div><i style={{width:"86%"}}/></div></div><div className="notice">Evidence suggests the current Junior Developer role uses the certified skill pathway. This is a relevance signal, not an automatic quality score.</div></Section></div>}

export function OutcomePage(){const {data}=useDemo();const t=data.trainees[0];return <div className="page"><PageHeader eyebrow="TRAINEE / OUTCOME" title="Current livelihood outcome" sub="The outcome record combines self-report, employer evidence, documents and follow-up signals."/><div className="detailHero"><div><span className="eyebrow">CURRENT OUTCOME</span><h2>{t.outcome}</h2><p>{t.role} • {t.employer} • {t.wage}</p></div><TrustScore value={t.trust}/><StatusBadge type="positive">VERIFIED</StatusBadge></div><div className="grid2"><Section title="Evidence signals" eyebrow="WHY THIS RECORD IS TRUSTED"><div className="scoreExplain">{[["Base source","+40"],["Employer verified","+20"],["Documents","+20"],["Recent update","+15"],["Consistent history","+10"],["Anomaly penalty","−18"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></Section><Section title="Outcome details" eyebrow="STRUCTURED RECORD"><div className="consent"><span>Job role</span><b>{t.role}</b></div><div className="consent"><span>Employer</span><b>{t.employer}</b></div><div className="consent"><span>Wage band</span><b>{t.wage}</b></div><div className="consent"><span>Training relevance</span><b>High</b></div><div className="consent"><span>Last updated</span><b>12 Sep 2026</b></div></Section></div></div>}

export function EmployerVerifyPage(){const {updateTrainee}=useDemo();const [done,setDone]=useState(false);const [employed,setEmployed]=useState(true);return <div className="page" style={{maxWidth:900}}><div className="verifyBox"><ShieldCheck size={48}/><span className="eyebrow">SECURE PUBLIC VERIFICATION • TOKEN VALID</span><h2>Employment Verification</h2><p>TechNova Solutions is being asked to confirm a limited set of employment facts for Amit S******.</p>{!done?<><div className="formGrid" style={{textAlign:"left",marginTop:25}}><label>Is the trainee currently employed?<select value={employed?"yes":"no"} onChange={e=>setEmployed(e.target.value==="yes")}><option value="yes">Yes</option><option value="no">No</option></select></label>{employed&&<><label>Job role<input defaultValue="Junior Developer"/></label><label>Joining month/year<input defaultValue="06/2026"/></label><label>Wage band<select><option>₹20k–25k</option><option>₹15k–20k</option><option>₹25k–30k</option></select></label></>}</div><button className="btn primary big" style={{marginTop:20}} onClick={()=>{updateTrainee("KSL-2026-00481",{verification:"Employer verified",trust:Math.min(100,95),anomaly:false,followup:"Employer verified"});setDone(true)}}>Confirm Employment</button><p style={{marginTop:15}}>Token expires 24 Sep 2026 • 23:59 IST. No unnecessary personal information is exposed.</p></>:<><CheckCircle2 size={42}/><h2>Verification Submitted</h2><p>Outcome record updated in the local demo state. Trust score recalculated from the new verification signal.</p><StatusBadge type="positive">VERIFICATION RECEIVED</StatusBadge></>}</div></div>}

export function EmployerRequestsPage(){return <div className="page"><PageHeader eyebrow="EMPLOYER / REQUESTS" title="Verification requests" sub="Confirm employment facts without accessing unnecessary trainee information."/><div className="cards">{[["Amit S******","Full Stack Web Development","Jun 2026","₹20k–25k"],["Priya S******","Advanced Solar Technician","Jul 2026","₹15k–20k"]].map((x,i)=><div className="outcomeCard" key={i}><div><span className="eyebrow">TOKEN VRF-{240+i}</span><h3>{x[0]}</h3><p>{x[1]} • Joining {x[2]} • {x[3]}</p></div><Link className="btn primary" to="/employer/verify/demo-token">Review</Link></div>)}</div></div>}

export function AuditLogsPage(){const rows=[["10:32 AM","Provider Admin","Outcome","VERIFY","KSL-2026-00481","verification: pending → verified"],["10:14 AM","Field Officer","Document","UPLOAD","DOC-7741","joining-letter.pdf added"],["09:51 AM","Employer","Outcome","CONFIRM","KSL-2026-00482","employment confirmed"],["09:22 AM","Scheme Admin","Anomaly","REVIEW","AN-0192","status: open → reviewed"],["08:48 AM","Trainee","Consent","UPDATE","SO-2026-00481","job sharing withdrawn"]];return <div className="page"><PageHeader eyebrow="ADMIN / GOVERNANCE" title="Audit logs" sub="Immutable-style activity view for critical outcome, consent, verification and evidence actions."/><div className="filters"><input placeholder="Filter entity ID…"/><select><option>All roles</option><option>Provider Admin</option><option>Employer</option><option>Field Officer</option></select><button className="btn"><Download size={14}/> Export log</button></div><DataTable headers={["Time","User","Entity","Action","Entity ID","Changes"]} rows={rows}/></div>}

export function NotificationsPage(){const {data}=useDemo();return <div className="page"><PageHeader eyebrow="SYSTEM / NOTIFICATIONS" title="Notification center" sub="Operational events that need attention across the outcome lifecycle."/><div className="cards">{(data.notifications||[]).map(n=><div className="outcomeCard" key={n.id}><div><StatusBadge type={n.type==="Anomaly detected"?"warning":"positive"}>{n.type}</StatusBadge><h3>{n.text}</h3><p>{n.time}</p></div><button className="btn" onClick={()=>alert("Notification opened in demo mode.")}>Open</button></div>)}</div></div>}

export function FieldVerificationPage(){const {data,updateTrainee}=useDemo();const [id,setId]=useState(data.trainees[4].id);const t=data.trainees.find(x=>x.id===id)||data.trainees[4];return <div className="page"><PageHeader eyebrow="FIELD OFFICER / VERIFICATION" title="Field verification workspace" sub="Capture visit evidence and verification results for outcomes that need independent confirmation."/><div className="grid2"><Section title="Assigned case" eyebrow={t.id}><div className="consent"><span>Trainee</span><b>{t.name}</b></div><div className="consent"><span>District</span><b>{t.district}</b></div><div className="consent"><span>Outcome</span><b>{t.outcome}</b></div><div className="consent"><span>Current trust</span><b>{t.trust}/100</b></div><select style={{width:"100%",marginTop:15}} value={id} onChange={e=>setId(e.target.value)}>{data.trainees.map(x=><option key={x.id} value={x.id}>{x.id} — {x.name}</option>)}</select></Section><Section title="Visit verification form" eyebrow="EVIDENCE CAPTURE"><div className="formGrid"><label>Status<select><option>Verified</option><option>Unable to verify</option><option>Revisit required</option></select></label><label>Visit date<input type="date" defaultValue="2026-09-24"/></label><label style={{gridColumn:"1/-1"}}>Evidence reference<input defaultValue="FIELD-VISIT-2026-0924-018"/></label><label style={{gridColumn:"1/-1"}}>Notes<textarea defaultValue="Employer site visited. Employment details cross-checked with available records."/></label></div><button className="btn primary" onClick={()=>{updateTrainee(t.id,{verification:"Field verified",trust:Math.min(100,t.trust+6),anomaly:false});alert("Field verification saved.")}}>Submit verification</button></Section></div></div>}

export function FieldHistoryPage(){return <div className="page"><PageHeader eyebrow="FIELD OFFICER / HISTORY" title="Verification history" sub="Completed field visits and evidence references."/><DataTable headers={["Date","Trainee","District","Result","Evidence","Officer"]} rows={[["24 Sep 2026","Rohit Verma","Noida","Verified","FIELD-VISIT-2026-0924-018","FO-104"],["20 Sep 2026","Meena Devi","Meerut","Verified","PHOTO+INVOICE-448","FO-104"],["18 Sep 2026","Sana Khan","Ghaziabad","Revisit required","VISIT-441","FO-102"]]}/></div>}

export function ProviderFollowupsPage(){return <FollowupCenterPage/>}
export function TraineeDashboardEnhanced(){const {data}=useDemo();const t=data.trainees[0];return <div className="page"><PageHeader eyebrow="TRAINEE / PERSONAL COMMAND CENTER" title={`Welcome, ${t.name}`} sub="Your complete journey from training to sustained livelihood." action={<Link className="btn ghost" to="/trainee/consent">Privacy & consent</Link>}/><div className="detailHero"><div><span className="eyebrow">SKILL OUTCOME ID</span><h2>{t.id}</h2><p>Current outcome • {t.outcome} • Last updated 12 Sep 2026</p></div><TrustScore value={t.trust}/></div><Kpis items={[["Training","Completed"],["Certificate","Verified"],["Outcome",t.outcome],["Employer",t.employer],["Wage",t.wage],["Retention","90D verified"]]}/><Section title="Journey" eyebrow="TRAINING → SUSTAINED LIVELIHOOD"><div className="journey">{["Training","Certification","Employment","Verification","30 Days","90 Days","180 Days","365 Days","Sustained"].map((x,i)=><div className="journeyStep" key={x}><b>{i+1}</b><span>{x}</span><small>{i<6?"Evidence":"Upcoming"}</small></div>)}</div></Section><div className="grid2"><Section title="Documents" eyebrow="EVIDENCE"><div className="cards">{docs.slice(0,3).map(d=><div className="docCard" key={d[0]}><FileText size={20}/><div><b>{d[0]}</b><span>{d[2]}</span></div></div>)}</div><Link className="btn ghost" style={{marginTop:12}} to="/trainee/documents">View all documents</Link></Section><Section title="Follow-ups" eyebrow="RETENTION"><div className="timeline">{followups.slice(0,3).map(x=><div key={x[0]}><i/><div><b>{x[0]} — {x[2]}</b><small>{x[1]} • {x[3]}</small></div></div>)}</div></Section></div></div>}

export function ProviderDetailPage(){const p=providers[0];return <div className="page"><PageHeader eyebrow="ADMIN / PROVIDER DETAIL" title={p[0]} sub={`${p[1]} • ${p[2]} • Provider analytics and verification coverage.`}/><Kpis items={[["Trainees",p[4]],["Courses",p[3]],["Placement",p[5]],["Retention",p[6]],["Trust",p[7]+"/100"],["Anomalies","3"]]}/><div className="grid2"><Section title="Outcome performance"><div className="chartBox"><PlacementChart/></div></Section><Section title="Retention"><div className="chartBox"><RetentionChart/></div></Section></div><Section title="Provider controls" eyebrow="GOVERNANCE"><div className="actionRow"><button className="btn primary">Request verification refresh</button><button className="btn">View audit trail</button><button className="btn">Export provider report</button></div></Section></div>}
export function SettingsPage(){return <div className="page"><PageHeader eyebrow="SYSTEM / SETTINGS" title="Workspace settings" sub="Demo preferences and accessibility controls."/><Section title="Interface"><div className="consent"><span>Compact data tables</span><button className="btn primary">Enabled</button></div><div className="consent"><span>Reduced motion</span><button className="btn">Off</button></div><div className="consent"><span>High contrast focus</span><button className="btn primary">Enabled</button></div></Section><Section title="Demo environment"><div className="notice">All prototype actions are stored locally in this browser. No real government or trainee data is transmitted in demo mode.</div></Section></div>}
