import React,{useState} from "react";
import {Download,FileText,MapPinned,ShieldCheck,TrendingUp,Users,BriefcaseBusiness,CheckCircle2,Clock3} from "lucide-react";
import {useDemo} from "../context/DemoContext";
import PageHeader from "../components/ui/PageHeader";
import StatusBadge from "../components/ui/StatusBadge";

const coverage=[
 ["Verified signal",34,"#67dcae"],
 ["Confirmed trainee",28,"#9ac9bd"],
 ["Self-reported",26,"#e2c176"],
 ["Unconfirmed",12,"#c57972"]
];

function Section({title,eyebrow,children,action}){return <section className="panel pageSection"><div className="panelHead"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h3>{title}</h3></div>{action}</div>{children}</section>}
function CoverageBadge({value="82% covered"}){return <span className="coverageBadge"><ShieldCheck size={13}/>{value}</span>}
function CoverageBar(){return <div className="coverageBar">{coverage.map(([label,value,color])=><i key={label} title={`${label}: ${value}%`} style={{width:`${value}%`,background:color}}/> )}</div>}
function Metric({label,value,detail}){return <div className="miniKpi"><span>{label}</span><b>{value}</b><small>{detail}</small></div>}

export function AdminEquityPage(){
 const groups=[["Women","78%","-2 pts","n=412"],["Men","80%","Reference","n=688"],["Rural","74%","-6 pts","n=389"],["Urban","82%","Reference","n=711"],["SC/ST","72%","-8 pts","n=301"],["Other categories","80%","Reference","n=799"]];
 return <div className="page"><PageHeader eyebrow="ADMIN / EQUITY" title="Equity and inclusion" sub="Outcome gaps are shown with coverage and sample context. Small groups are suppressed instead of being over-interpreted."/><div className="notice"><ShieldCheck size={16}/> Demographic fields are consent-based. Values below are demo aggregates and are suppressed when the sample is below 10 records.</div><div className="metricGrid"><Metric label="Overall placement" value="78.4%" detail="Coverage: 82%"/><Metric label="6M retention gap" value="6 pts" detail="Rural vs urban"/><Metric label="Wage progression" value="+18%" detail="Verified coverage: 64%"/><Metric label="Data coverage" value="82%" detail="All dimensions"/></div><Section title="Placement by group" eyebrow="REFERENCE-GROUP COMPARISON" action={<CoverageBadge/>}><div className="equityGrid">{groups.map(([name,value,gap,sample])=><div className="equityRow" key={name}><div><b>{name}</b><small>{sample}</small></div><strong>{value}</strong><span className={gap.startsWith("-")?"negative":"positiveText"}>{gap}</span></div>)}</div></Section><Section title="Coverage by metric" eyebrow="CONFIDENCE CONTEXT"><CoverageBar/><div className="legend">{coverage.map(([label,value])=><span key={label}><i/>{label} {value}%</span>)}</div></Section></div>
}

export function SkillGapsPage(){
 const [course,setCourse]=useState("All courses");
 const gaps=[["Power BI","Full Stack Web Development",86,"41% of employed trainees","n=86"],["Advanced diagnostics","Electric Vehicle Service",63,"34% of employed trainees","n=52"],["Customer acquisition","Digital Marketing",48,"29% of self-employed trainees","n=41"],["Patient documentation","Healthcare Assistant",31,"22% of employed trainees","n=27"]];
 const rows=course==="All courses"?gaps:gaps.filter(x=>x[1]===course);
 return <div className="page"><PageHeader eyebrow="ADMIN / SKILL GAPS" title="Curriculum skill-gap monitor" sub="Compare skills taught with skills required in reported roles. Gaps are shown only when the sample is large enough to be useful."/><div className="filters"><select value={course} onChange={e=>setCourse(e.target.value)}><option>All courses</option>{[...new Set(gaps.map(x=>x[1]))].map(x=><option key={x}>{x}</option>)}</select><CoverageBadge value="Minimum sample: 10"/></div><Section title="Priority gaps" eyebrow="TRAINING VS JOB REQUIREMENTS"><div className="gapList">{rows.map(([skill,courseName,score,share,sample])=><div className="gapRow" key={skill}><div><b>{skill}</b><span>{courseName} | {share} | {sample}</span></div><strong>{score}%<small>affected</small></strong><div className="progressTrack"><i style={{width:`${score}%`}}/></div><button className="btn" onClick={()=>alert(`Advisory detail prepared for ${skill}.`)}>Inspect</button></div>)}</div></Section><Section title="Recommended action" eyebrow="ADVISORY SIGNAL"><div className="notice"><TrendingUp size={16}/> Add Power BI fundamentals to the next Full Stack Web Development curriculum review. The recommendation is based on recurring requirements across verified and confirmed outcomes.</div></Section></div>
}

export function DataQualityPage(){
 const districts=[["Ghaziabad","91%","88%","84%"],["Lucknow","78%","74%","71%"],["Noida","86%","81%","79%"],["Meerut","69%","63%","58%"]];
 return <div className="page"><PageHeader eyebrow="ADMIN / DATA QUALITY" title="Coverage and confidence" sub="See where metrics are supported by verification, follow-ups, and consented evidence before acting on them."/><div className="metricGrid"><Metric label="Outcome coverage" value="86%" detail="4,141 of 4,821 records"/><Metric label="Verification coverage" value="84.6%" detail="Employer, field, or signal"/><Metric label="Follow-up coverage" value="79.2%" detail="At least one response"/><Metric label="Unconfirmed" value="12%" detail="Requires outreach"/></div><Section title="District coverage heatmap" eyebrow="LOCATION QUALITY"><div className="qualityTable"><div className="qualityHead"><span>District</span><span>Verified</span><span>Follow-up</span><span>Consent</span></div>{districts.map(row=><div className="qualityRow" key={row[0]}>{row.map((cell,index)=><span key={cell} className={index>0&&Number.parseInt(cell,10)<70?"qualityLow":""}>{cell}</span>)}</div>)}</div></Section><Section title="Metric coverage legend" eyebrow="PUBLISHED WITH EVERY CHART"><CoverageBar/><div className="legend">{coverage.map(([label,value])=><span key={label}><i/>{label}: {value}%</span>)}</div><div className="notice"><MapPinned size={16}/> Low-coverage cells are marked provisional and should not be used for provider ranking until follow-up coverage improves.</div></Section></div>
}

export function AdvisoryReportsPage(){
 const [generated,setGenerated]=useState(false);
 return <div className="page"><PageHeader eyebrow="ADMIN / ADVISORY REPORTS" title="Quarterly curriculum advisory" sub="Turn outcome evidence into practical curriculum actions for providers and scheme administrators." action={<button className="btn primary" onClick={()=>setGenerated(true)}><FileText size={15}/> Generate Q3 report</button>}/><Section title="Report readiness" eyebrow="2026 Q3"><div className="metricGrid"><Metric label="Cohort size" value="4,821" detail="Across 4 providers"/><Metric label="Top gap" value="Power BI" detail="41% of affected jobs"/><Metric label="Reason signal" value="Salary" detail="18% of non-placement"/><Metric label="Coverage" value="82%" detail="Report confidence"/></div></Section><Section title="Report contents" eyebrow="GENERATED FROM DEMO DATA"><div className="reportRows">{["Executive summary","Top skill gaps by course","Non-placement and attrition reasons","Context-adjusted provider scorecards","Coverage and confidence appendix"].map((x,i)=><div key={x}><CheckCircle2 size={16}/><span>{x}</span><StatusBadge type={i<4?"positive":"neutral"}>{i<4?"READY":"APPENDIX"}</StatusBadge></div>)}</div>{generated&&<div className="notice"><CheckCircle2 size={16}/> Report generated in demo mode. PDF and CSV export actions are ready for API-backed file generation.</div>}<div className="actionRow"><button className="btn" onClick={()=>alert("Demo PDF export prepared.")}><Download size={14}/> Download PDF</button><button className="btn" onClick={()=>alert("Demo CSV export prepared.")}><Download size={14}/> Download CSV</button></div></Section></div>
}

export function ProviderScorecardPage(){
 const metrics=[["Completion","89%","Coverage 94%"],["Employment @6mo","67%","Coverage 82%"],["12M retention","58%","Coverage 61%"],["Wage progression","+18%","Coverage 64%"],["Job relevance","74%","Coverage 78%"],["Adjusted score","76/100","Provisional"]];
 return <div className="page"><PageHeader eyebrow="PROVIDER / SCORECARD" title="Context-adjusted provider scorecard" sub="Raw and adjusted measures are shown together so placement outcomes are not separated from context or data coverage."/><div className="notice"><ShieldCheck size={16}/> Adjusted score is provisional while follow-up coverage is below 70%. It is not a ranking or penalty.</div><div className="metricGrid">{metrics.map(([label,value,detail])=><Metric key={label} label={label} value={value} detail={detail}/>)}</div><div className="grid2"><Section title="Course drill-down" eyebrow="RAW VS EXPECTED"><div className="scorecardRows">{[["Full Stack Web Development","82%","78%","+4 pts"],["Advanced Solar Technician","81%","79%","+2 pts"],["EV Service Associate","74%","77%","-3 pts"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>Expected {x[2]}</small><strong>{x[3]}</strong></div>)}</div></Section><Section title="Coverage profile" eyebrow="TRUST CONTEXT"><CoverageBar/><div className="legend">{coverage.map(([label,value])=><span key={label}><i/>{label} {value}%</span>)}</div></Section></div><Section title="Priority improvement" eyebrow="NEXT ACTION"><div className="notice"><BriefcaseBusiness size={16}/> Review Power BI and advanced diagnostics requirements with employers before the next cohort starts.</div></Section></div>
}

export function OpportunitiesPage(){
 const {data}=useDemo();
 const trainee=data.trainees[0];
 const [shared,setShared]=useState(true);
 const opportunities=[["Junior Developer","TechNova Solutions","Ghaziabad","₹20k–25k","82% skill match"],["Solar Installation Technician","SuryaGrid Energy","Ghaziabad","₹15k–20k","76% skill match"],["EV Service Associate","VoltDrive Motors","Noida","₹15k–20k","71% skill match"]];
 return <div className="page"><PageHeader eyebrow="TRAINEE / OPPORTUNITIES" title="Opportunities matched to your skills" sub="Job sharing is optional. Your current consent setting controls whether recommendations are shown." action={<button className={"btn "+(shared?"primary":"ghost")} onClick={()=>setShared(value=>!value)}>{shared?"Job sharing enabled":"Enable job sharing"}</button>}/>{shared?<><div className="notice"><Users size={16}/> Recommendations are based on {trainee.course} and your consented district. Employers do not receive your profile until you choose to apply.</div><div className="cards">{opportunities.map(x=><div className="outcomeCard" key={x[0]}><div><span className="eyebrow">{x[4]}</span><h3>{x[0]}</h3><p>{x[1]} | {x[2]} | {x[3]}</p></div><button className="btn primary" onClick={()=>alert(`Interest recorded for ${x[0]}.`)}>View role</button></div>)}</div><Section title="Response incentive wallet" eyebrow="DEMO REWARDS"><div className="metricGrid"><Metric label="Follow-ups completed" value="2" detail="Consistent responses"/><Metric label="Reward status" value="Priority access" detail="Mock incentive earned"/><Metric label="Next checkpoint" value="180 days" detail="Complete to maintain eligibility"/></div></Section></>:<div className="verifyBox"><Clock3 size={32}/><h2>Job sharing is paused</h2><p>Enable job sharing when you want to see nearby opportunities. This change is local to the demo and can be reversed immediately.</p></div>}</div>
}
