import React from "react";
import {BrowserRouter,Routes,Route,Navigate} from "react-router-dom";
import {DemoProvider} from "./context/DemoContext"; import {AuthProvider} from "./context/AuthContext";
import PublicLayout from "./layouts/PublicLayout"; import DashboardLayout from "./layouts/DashboardLayout"; import ProtectedRoute from "./routes/ProtectedRoute";
import LandingPage from "./pages/public/LandingPage"; import LoginPage from "./pages/public/LoginPage"; import RegisterPage from "./pages/public/RegisterPage"; import ClaimRecordPage from "./pages/public/ClaimRecordPage";
import AdminDashboard from "./pages/admin/AdminDashboard"; import ProvidersPage from "./pages/admin/ProvidersPage"; import CoursesPage from "./pages/admin/CoursesPage"; import AnomalyReviewPage from "./pages/admin/AnomalyReviewPage";
import ProviderDashboard from "./pages/provider/ProviderDashboard"; import TraineesPage from "./pages/provider/TraineesPage"; import TraineeDetailPage from "./pages/provider/TraineeDetailPage"; import OutcomesPage from "./pages/provider/OutcomesPage"; import ReportsPage from "./pages/provider/ReportsPage";
import FieldDashboard from "./pages/field/FieldDashboard"; import EmployerDashboard from "./pages/employer/EmployerDashboard";
import RoleRoute from "./routes/RoleRoute";
import {AdminAnalyticsPage,AdminOutcomesPage,ProviderAnalyticsPage,FollowupCenterPage,DocumentsPage,ConsentPage,TrainingPage,OutcomePage,EmployerVerifyPage,EmployerRequestsPage,AuditLogsPage,NotificationsPage,FieldVerificationPage,FieldHistoryPage,TraineeDashboardEnhanced,ProviderDetailPage,SettingsPage} from "./pages/ExpandedPages";
import {AdminEquityPage,SkillGapsPage,DataQualityPage,AdvisoryReportsPage,ProviderScorecardPage,OpportunitiesPage} from "./pages/InsightsPages";
function Shell(){return <ProtectedRoute><DashboardLayout/></ProtectedRoute>}
export default function App(){return <AuthProvider><DemoProvider><BrowserRouter><Routes>
<Route element={<PublicLayout/>}><Route path="/" element={<LandingPage/>}/><Route path="/login" element={<LoginPage/>}/><Route path="/register" element={<RegisterPage/>}/><Route path="/claim-record" element={<ClaimRecordPage/>}/></Route>
<Route element={<Shell/>}>
<Route path="/dashboard" element={<RoleHome/>}/>
<Route path="/trainees" element={<TraineesPage/>}/><Route path="/trainees/:id" element={<TraineeDetailPage/>}/>
<Route path="/outcomes" element={<OutcomesPage/>}/><Route path="/reports" element={<ReportsPage/>}/><Route path="/anomalies" element={<AnomalyReviewPage/>}/><Route path="/providers" element={<ProvidersPage/>}/><Route path="/courses" element={<CoursesPage/>}/>
<Route element={<RoleRoute allow={["admin"]}/>}><Route path="/admin/dashboard" element={<AdminDashboard/>}/><Route path="/admin/providers" element={<ProvidersPage/>}/><Route path="/admin/providers/:id" element={<ProviderDetailPage/>}/><Route path="/admin/courses" element={<CoursesPage/>}/><Route path="/admin/outcomes" element={<AdminOutcomesPage/>}/><Route path="/admin/analytics" element={<AdminAnalyticsPage/>}/><Route path="/admin/anomaly-review" element={<AnomalyReviewPage/>}/><Route path="/admin/audit-logs" element={<AuditLogsPage/>}/><Route path="/admin/equity" element={<AdminEquityPage/>}/><Route path="/admin/skill-gaps" element={<SkillGapsPage/>}/><Route path="/admin/data-quality" element={<DataQualityPage/>}/><Route path="/admin/advisory-reports" element={<AdvisoryReportsPage/>}/></Route>
<Route element={<RoleRoute allow={["provider_admin","provider"]}/>}><Route path="/provider/dashboard" element={<ProviderDashboard/>}/><Route path="/provider/trainees" element={<TraineesPage/>}/><Route path="/provider/trainees/:id" element={<TraineeDetailPage/>}/><Route path="/provider/outcomes" element={<OutcomesPage/>}/><Route path="/provider/follow-ups" element={<FollowupCenterPage/>}/><Route path="/provider/reports" element={<ReportsPage/>}/><Route path="/provider/analytics" element={<ProviderAnalyticsPage/>}/><Route path="/provider/scorecard" element={<ProviderScorecardPage/>}/></Route>
<Route element={<RoleRoute allow={["employer"]}/>}><Route path="/employer/dashboard" element={<EmployerDashboard/>}/><Route path="/employer/verification-requests" element={<EmployerRequestsPage/>}/><Route path="/employer/confirmed" element={<EmployerDashboard/>}/></Route><Route path="/employer/verify/:token" element={<EmployerVerifyPage/>}/>
<Route element={<RoleRoute allow={["field_officer","field"]}/>}><Route path="/field/officer/dashboard" element={<FieldDashboard/>}/><Route path="/field/officer/assigned" element={<FieldDashboard/>}/><Route path="/field/officer/verification" element={<FieldVerificationPage/>}/><Route path="/field/officer/history" element={<FieldHistoryPage/>}/></Route>
<Route element={<RoleRoute allow={["trainee"]}/>}><Route path="/trainee/dashboard" element={<TraineeDashboardEnhanced/>}/><Route path="/trainee/training" element={<TrainingPage/>}/><Route path="/trainee/outcome" element={<OutcomePage/>}/><Route path="/trainee/follow-ups" element={<FollowupCenterPage traineeMode/>}/><Route path="/trainee/documents" element={<DocumentsPage traineeMode/>}/><Route path="/trainee/consent" element={<ConsentPage/>}/><Route path="/trainee/opportunities" element={<OpportunitiesPage/>}/></Route>
<Route element={<RoleRoute allow={["admin","provider_admin","provider","employer","field_officer","field","trainee"]}/>}><Route path="/trainees" element={<TraineesPage/>}/><Route path="/trainees/:id" element={<TraineeDetailPage/>}/><Route path="/outcomes" element={<OutcomesPage/>}/><Route path="/reports" element={<ReportsPage/>}/><Route path="/anomalies" element={<AnomalyReviewPage/>}/><Route path="/providers" element={<ProvidersPage/>}/><Route path="/courses" element={<CoursesPage/>}/><Route path="/documents" element={<DocumentsPage/>}/><Route path="/follow-ups" element={<FollowupCenterPage/>}/><Route path="/notifications" element={<NotificationsPage/>}/><Route path="/settings" element={<SettingsPage/>}/></Route>
</Route>
<Route path="*" element={<Navigate to="/" replace/>}/>
</Routes></BrowserRouter></DemoProvider></AuthProvider>}
function RoleHome(){const r=localStorage.getItem("tr-role");if(r==="provider"||r==="provider_admin")return <ProviderDashboard/>;if(r==="field"||r==="field_officer")return <FieldDashboard/>;if(r==="employer")return <EmployerDashboard/>;if(r==="trainee")return <TraineeDashboardEnhanced/>;return <Navigate to="/login" replace/>}
